///|
#doc(hidden)
#deprecated
pub extend SqliteError with @moonbitlang/core/debug.Debug::{to_repr}

///|
#doc(hidden)
#deprecated
pub extend SqliteError with Eq::{equal, not_equal}

///|
#doc(hidden)
#deprecated
pub extend ErrorCode with @moonbitlang/core/debug.Debug::{to_repr}

///|
#doc(hidden)
#deprecated
pub extend ErrorCode with Eq::{equal, not_equal}

///|
#doc(hidden)
#deprecated
pub extend ExtendedCode with @moonbitlang/core/debug.Debug::{to_repr}

///|
#doc(hidden)
#deprecated
pub extend ExtendedCode with Eq::{equal, not_equal}
